language: python
python:
        - "2.7"
          #- "3.2" I'd really love this to work but it doesn't
        - "3.4"
# command to install dependencies
install: 
        - "pip install -r test_requirements.txt"
        - "pip install -r requirements.txt"
# command to run tests
script: python setup.py test
